### ISSUE TITLE
Failed to scan for Bluetooth devices

### ISSUE THREAD

**Issue by sjvudp** [OpenTracks/OpenTracks#1]
On a Huawei P10 Lite (Android 8.0) I had Bluetooth and location services enabled, and one app was recording a route while also recording the heart rate from a Bluetooth device. I had set up OpenTracks to record the route in parallel, too, and I wanted it to record the heart rate, too.
However when trying to add the heart rate device, I only got an error message (sorry, I didn't save it) that the app cannot scan for Bluetooth devices.
Maybe I should mention that the German "Corona Warn App" was active, too. That could have implications, but I don't really know.
The version being used was 3.9.4.

**Comment by jeichelbaum** [comment]
I believe you might be looking for another app / repository. I will close the issue, because it is unrelated to this project, which features no heart rate or route recording. Feel free to reopen the issue.

**Comment by sjvudp** [comment]
Ah, seems I really meant "OpenTracksApp". Sorry.
